name: Test Automation CI
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Start docker
        run: docker compose up -d
      - name: Install dependencies & Run tests
        uses: cypress-io/github-action@v6
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report
